server:
    port: 8080
    servlet: 
        context-path: /api

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ms_order?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: root
        password: root

    jpa:
        show-sql: true
        # defer-datasource-initialization: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    
    # Producer properties
    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            group-id: group_id

    application:
        name: ms.order
    
    main:
        allow-bean-definition-overriding: true

topic:
    name:
        producer: order_history_kafka

# Common Kafka Properties
auto:
    create:
        topics:
            enable: true