spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/usf?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: root
        password: root

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                ddl-auto: create
                dialect: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true

server:
    servlet:
        context-path: /api